# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build

on: 
  workflow_call:
  
defaults:
  run:
    working-directory: ./csharp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Get infos about .NET projects
      if: ${{ env.GH_TOKEN != '' }}
      run: |
        DOTNET_INFO=$(dotnet list package)
        gh variable set DOTNET_INFO --body "$DOTNET_INFO"
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
